<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <PackageId>Iavory.ObservableOptions</PackageId>
        <Version>1.3.0</Version>
        <Authors>Silas Meyer</Authors>
        <Description>Observable options with INotifyPropertyChanged support</Description>
        <PackageTags>options;mvvm;observable</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <RepositoryUrl>https://github.com/SilasMeyer4/Iavory.ObservableOptions</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

</Project>
